<?php
/**
 * @file
 * Main module file for the Coordinate Field module
 */

/**
 * Implements hook_field_info()
 */
function coordinate_field_field_info() {
  return array(
    'coordinate_field' => array(
      'label' => t('Coordinate'),
      'description' => t('Store X and Y coordinate values.'),
      'settings' => array(
        'unit' => 'px',
      ),
      'default_widget' => 'coordinate_field_widget',
      'default_formatter' => 'coordinate_field_default',
    ),
  );
}

/**
 * Implements hook_field_settings_form()
 */
function coordinate_field_field_settings_form($field, $instance) {
  $defaults = field_info_field_settings($field['type']);
  $settings = array_merge($defaults, $field['settings']);

  $scheme_options = array();

  // @todo:
  // Add more units for support as needed.
  $units = array('px' => 'Pixels');

  $form['unit'] = array(
    '#title' => t('Coordinate Unit'),
    '#description' => t('Which unit of measure our coordinates will be in.'),
    '#type' => 'select',
    '#options' => $units,
    '#default_value' => $settings['unit'],
  );

  return $form;
}

/**
 * Implements hook_field_widget_info()
 */
function coordinate_field_field_widget_info() {
  return array(
    'coordinate_field_widget' => array(
      'label' => t('Default'),
      'description' => t('Input X and Y values.'),
      'field types' => array('coordinate_field'),
      'behaviors' => array(
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_form()
 */
function coordinate_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $field_settings = $field['settings'];

  switch ($field['type']) {
    case 'coordinate_field':
      // Not sure why we have to manually add the field name to the widget,
      // but seems like we do.
      $element['label'] = array(
        '#markup' => theme('html_tag', array(
          'element' => array(
            '#tag' => 'label',
            '#value' => filter_xss($instance['label']),
          ),
        )),
      );

      $element['position_x'] = array(
        '#title' => t('X'),
        '#type' => 'textfield',
        '#size' => 15,
        '#prefix' => '<div class="container-inline">',
        '#suffix' => $field_settings['unit'] . '</div>',
        '#default_value' => isset($items[$delta]['position_x']) ? $items[$delta]['position_x'] : '',
      );

      $element['position_y'] = array(
        '#title' => t('Y'),
        '#type' => 'textfield',
        '#size' => 15,
        '#prefix' => '<div class="container-inline">',
        '#suffix' => $field_settings['unit'] . '</div>',
        '#default_value' => isset($items[$delta]['position_y']) ? $items[$delta]['position_y'] : '',
      );
      break;
  }

  return $element;
}

/**
 * Implements hook_field_validate().
 */
function coordinate_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!coordinate_field_field_is_empty($item, $field)) {
      // Check that X is a number
      if (!is_numeric($item['position_x'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'coordinate_field_invalid_position_x',
          'message' => t('X Coordinate must be an integer or decimal.'),
        );
      }

      // Check that Y is a number
      if (!is_numeric($item['position_y'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'coordinate_field_invalid_position_y',
          'message' => t('Y Coordinate must be an integer or decimal.'),
        );
      }
    }
  }
}

/**
 * Implements hook_field_widget_error().
 */
function coordinate_field_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'coordinate_field_invalid_position_x':
      form_error($element['position_x'], $error['message']);
      break;
    case 'coordinate_field_invalid_position_y':
      form_error($element['position_y'], $error['message']);
      break;
  }
}

/**
 * Implements hook_field_is_empty()
 */
function coordinate_field_field_is_empty($item, $field) {
  if (empty($item['position_x']) && empty($item['position_y'])) {
    return TRUE;
  }
}


/**
 * Implements hook_theme().
 */
function coordinate_field_theme() {
  return array(
    'coordinate_field_formatter_coord_default' => array(
      'variables' => array('element' => NULL, 'display' => NULL, 'field' => NULL, 'instance' => NULL),
    ),
    'coordinate_field_formatter_coord_xpos' => array(
      'variables' => array('element' => NULL, 'field' => NULL, 'instance' => NULL),
    ),
    'coordinate_field_formatter_coord_ypos' => array(
      'variables' => array('element' => NULL, 'field' => NULL, 'instance' => NULL),
    ),
  );
}

/**
 * Implements hook_field_formatter_info()
 */
function coordinate_field_field_formatter_info() {
  return array(
    'coord_default' => array(
      'label' => t('Default'),
      'field types' => array('coordinate_field'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
      'settings' => array(
        'display_unit' => TRUE,
      ),
    ),
    'coord_xpos' => array(
      'label' => t('X value'),
      'field types' => array('coordinate_field'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
    'coord_ypos' => array(
      'label' => t('Y value'),
      'field types' => array('coordinate_field'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function coordinate_field_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  if ($display['type'] == 'coord_default') {
    $element['display_unit'] = array(
      '#title' => t('Display unit'),
      '#type' => 'checkbox',
      '#default_value' => $settings['display_unit'],
    );
  }
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function coordinate_field_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  if ($display['type'] == 'coord_default') {
    if ($display['settings']['display_unit']) {
      return t('Display unit');
    }
    else {
      return t('Hide unit');
    }
  }
  return '';
}

/**
 * Implements hook_field_formatter_view().
 */
function coordinate_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $elements = array();
  foreach ($items as $delta => $item) {
    $elements[$delta] = array(
      '#theme' => 'coordinate_field_formatter_' . $display['type'],
      '#element' => $item,
      '#field' => $field,
      '#instance' => $instance,
      '#display' => $display,
    );
  }

  return $elements;
}


/**
 * Formats a coordinate
 */
function theme_coordinate_field_formatter_coord_default($vars) {

  $element = $vars['element'];
  $display = $vars['display'];
  $field = $vars['field'];
  $output = $element['position_x'] . ($display['settings']['display_unit'] ? $field['settings']['unit'] : '');
  $output .= ', ';
  $output .= $element['position_y'] . ($display['settings']['display_unit'] ? $field['settings']['unit'] : '');

  return ($output);

}

/**
 * Formats a coordinate
 */
function theme_coordinate_field_formatter_coord_xpos($vars) {

  return ($vars['element']['position_x']);

}

/**
 * Formats a coordinate
 */
function theme_coordinate_field_formatter_coord_ypos($vars) {

  return ($vars['element']['position_y']);

}
